services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - 5000:80
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=http://minio:9000
      - NOME_DO_BUCKET=${NOME_DO_BUCKET}
    depends_on:
      - minio

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: